import { createPendingPhotoDiagnostics } from "@hairfit/shared";
import { deriveConsultationJourney, type ConsultationPreview, type ConsultationSnapshot } from "./contracts";

export function createPreviewSlots(): ConsultationPreview[] {
  const axes = ["BALANCE", "IMAGE", "LIFESTYLE"] as const;
  return axes.flatMap((axis) => [1, 2, 3].map((position) => ({
    id: `${axis.toLowerCase()}-${position}`,
    axis,
    label: `${axis} ${position}`,
    reason: "generation 결과를 연결하면 전략 근거가 표시됩니다.",
    imageUrl: null,
    generatedImagePath: null,
    status: "pending" as const,
    sourceVariantId: null,
  })));
}

export function createConsultationSnapshot(input: { sessionId: string; userId: string; now?: string }): ConsultationSnapshot {
  const now = input.now ?? new Date().toISOString();
  const snapshot = {
    schemaVersion: 1,
    sessionId: input.sessionId,
    userId: input.userId,
    version: 1,
    lifecycleState: "draft" as const,
    currentStage: "discovery",
    completedStages: [],
    analysisRun: null,
    fashionBatch: null,
    hairColorGenerationRun: null,
    hairColorPreviewRuns: [],
    startContext: null,
    discovery: {
      purpose: "",
      goals: [],
      currentHair: "",
      hairLength: "중간",
      hairDensity: "보통",
      strandThickness: "보통",
      hairTexture: "직모",
      damageLevel: "낮음",
      treatmentHistory: [],
      desiredServices: [],
      allowedServices: [],
      maintenanceLevel: "medium",
      morningMinutes: 10,
      heatStyling: "sometimes",
      salonCycleWeeks: 8,
      changeLevel: "moderate",
      avoid: [],
      notes: "",
    },
    photo: {
      generationId: null, draftId: null, clientRequestId: null, uploadedAt: null, expiresAt: null,
      primaryUrl: null, colorAssistUrl: null, colorAssistDraftId: null, colorAssistUploadedAt: null, colorAssistExpiresAt: null,
      colorPrimaryCaptureAssetId: null, colorAssistCaptureAssetId: null, crop: null,
      quality: createPendingPhotoDiagnostics(),
      usageScopes: ["analysis", "preview"], retentionDays: 7, capturedAt: null,
    },
    evidence: { pipelineStatus: "idle", items: [], reviewedAt: null },
    faceAnalysis: { faceShape: "확인 전", balance: "확인 전", hairline: "확인 전", density: "확인 전", confidence: "low" },
    personalColor: { season: "확인 전", undertone: "확인 전", palette: [], confidence: "low" },
    personalColorDiagnosis: {
      state: "pending", evidenceId: null, qualityStatus: "unknown", qualityConfidence: null, warnings: [],
      primaryType: null, secondaryType: null, blend: {},
      axes: { temperature: null, value: null, chroma: null, contrast: null },
      palette: { best: [], neutrals: [], accents: [], caution: [], metals: [] },
      detailVersion: null, summary: "", bestColors: [], avoidColors: [], stylingPalette: [], hairColorHints: [], model: null,
      hairColorDirections: [],
      startedAt: null, completedAt: null, errorCode: null, errorMessage: null,
    },
    strategyRecommendations: [],
    strategy: { revision: 1, length: "medium", fringe: "open", parting: "natural", layerStart: "cheek", crownVolume: "medium", sideVolume: "low", texture: "natural", color: "natural", confirmedAt: null },
    previews: createPreviewSlots(),
    shortlist: { previewIds: [], updatedAt: null },
    finalist: { finalistPreviewId: null, backupPreviewId: null, decidedAt: null },
    selectedStyleHistory: [],
    colorDecision: {
      id: null, revision: 0, state: "not-applicable", selectionSnapshotId: null, personalColorEvidenceId: null,
      hairMask: null, catalogItemId: null, colorName: "현재 모발색", swatchHex: "#2B211D", technique: "full",
      targetLevel: null, intensity: 70, temperature: 0, saturation: 0, rootDepth: 20, candidates: [], bleachPolicy: "unknown", maintenance: "unknown",
      fadeDirection: "", warnings: [], instantSimulationPath: null, finalImageUrl: null, finalImagePath: null,
      generationAttemptId: null, inputFingerprint: null, confirmedAt: null, updatedAt: null,
    },
    salonBrief: { version: 1, mode: "customer", summary: "", cut: "", volumeTexture: "", styling: "", caution: [], shareExpiryHours: 24, shareRevokedAt: null, rawFaceIncluded: false, designerFeedback: null, createdAt: null },
    makeupDirection: { id: null, status: "not-started", confirmedAt: null, sourceFingerprint: null },
    result: { id: null, version: 0, state: "not-started", heroImageUrl: null, heroImagePath: null, headline: "", rationale: [], limitations: [], nextActions: [], selectionSnapshotId: null, colorSelectionSnapshotId: null, personalColorEvidenceId: null, salonBriefVersion: null, fashionLookId: null, fashionSelectedAt: null, fashionSourceColorSelectionId: null, compiledAt: null },
    actualService: { services: [], serviceDate: null, designerNotes: "", confirmedAt: null },
    careProgram: { actualServiceId: null, programVersion: 0, today: [], checkpoints: (["D+1", "D+3", "D+7", "D+30", "D+45", "D+90"] as const).map((offset) => ({ offset, action: "상태를 확인하고 필요한 관리만 기록해 주세요.", complete: false })), concerns: [], afterPhotoUrl: null, afterPhotoUpload: null, satisfaction: null },
    fashion: {
      direction: "",
      directionSnapshot: { situation: "daily", genre: "casual", season: "all-season", fit: "regular", exposure: "balanced", budget: "", avoidItems: [] },
      shortlistIds: [],
      lookId: null,
      category: null,
      label: "",
      items: [],
      palette: [],
      neckline: "",
      silhouette: "",
      avoidCombinations: [],
      shoppingKeywords: [],
      selectedAt: null,
      sourceColorSelectionId: null,
      staleReason: null,
    },
    createdAt: now,
    updatedAt: now,
  } satisfies Omit<ConsultationSnapshot, "journey">;
  return { ...snapshot, journey: deriveConsultationJourney(snapshot, snapshot.lifecycleState) };
}
