"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { LAUNCH_PROMOTION_CODE } from "../../lib/email-campaign";
import { Button } from "../ui/Button";
import { ConfirmActionDialog } from "../ui/ConfirmActionDialog";
import { Panel, SurfaceCard } from "../ui/Surface";

type Campaign={id:string;campaign_type:"service_notice"|"promotion";name:string;subject:string;promotion_code:string|null;eligibility_cutoff:string;claim_starts_at:string|null;claim_ends_at:string|null;scheduled_at:string|null;test_sent_at:string|null;status:string;counts:Record<string,number>};
type Payload={enabled:boolean;deliveryMode:string;campaigns:Campaign[];error?:string};
const isoLocal=(date:Date)=>new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);

export function AdminEmailCampaignComposer(){
  const now=useMemo(()=>new Date(),[]);
  const [campaignType,setCampaignType]=useState<"promotion"|"service_notice">("promotion");
  const [name,setName]=useState("HairFit 정식 출시 기존 회원 프로모션");
  const [code,setCode]=useState(LAUNCH_PROMOTION_CODE);
  const [subject,setSubject]=useState("(광고) HairFit 정식 출시 기념, 기존 회원 무료 풀스타일 1회권");
  const [preheader,setPreheader]=useState(`${LAUNCH_PROMOTION_CODE} 등록 후 30일 안에 무료 풀스타일 상담을 시작하세요.`);
  const [cutoff,setCutoff]=useState(isoLocal(now));
  const [claimStarts,setClaimStarts]=useState(isoLocal(new Date(now.getTime()+86400000)));
  const [claimEnds,setClaimEnds]=useState(isoLocal(new Date(now.getTime()+31*86400000)));
  const [scheduledAt,setScheduledAt]=useState(isoLocal(new Date(now.getTime()+86400000)));
  const [payload,setPayload]=useState<Payload|null>(null);const [preview,setPreview]=useState<{subject:string;preheader:string;html:string;text:string}|null>(null);
  const [busy,setBusy]=useState<string|null>(null);const [message,setMessage]=useState<string|null>(null);const [scheduleTarget,setScheduleTarget]=useState<Campaign|null>(null);const [confirmation,setConfirmation]=useState("");
  const load=useCallback(async()=>{const response=await fetch("/api/admin/email-campaigns",{cache:"no-store"});const next=await response.json().catch(()=>({})) as Payload;setPayload(next);},[]);
  useEffect(()=>{let active=true;void fetch("/api/admin/email-campaigns",{cache:"no-store"}).then(async response=>await response.json() as Payload).then(next=>{if(active)setPayload(next)});return()=>{active=false};},[]);
  const act=async(input:Record<string,unknown>)=>{setBusy(String(input.action));setMessage(null);const response=await fetch("/api/admin/email-campaigns",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)});const result=await response.json().catch(()=>({})) as {error?:string;preview?:typeof preview};setBusy(null);if(!response.ok){setMessage(result.error||"작업을 완료하지 못했습니다.");return false;}if(result.preview)setPreview(result.preview);setMessage("작업이 완료되었습니다.");await load();return true;};
  const create=()=>act({action:"create",campaignType,name,subject,preheader,promotionCode:code,eligibilityCutoff:new Date(cutoff).toISOString(),claimStartsAt:campaignType==="promotion"?new Date(claimStarts).toISOString():null,claimEndsAt:campaignType==="promotion"?new Date(claimEnds).toISOString():null});
  return <main className="f-admin-email-campaign grid gap-5 py-5">
    <Panel as="header" className="p-5"><p className="app-kicker">Launch communications</p><h1 className="mt-2 text-2xl font-black">캠페인 메일</h1><p className="mt-2 text-sm leading-6 text-[var(--app-muted)]">대상과 템플릿을 동결한 뒤 테스트 메일을 통과해야 예약할 수 있습니다. 관리자 요청에서 대량 메일을 직접 발송하지 않습니다.</p><p className="mt-2 text-xs font-bold">기능 {payload?.enabled?"ON":"OFF"} · 발송 모드 {payload?.deliveryMode||"off"}</p></Panel>
    {message?<p role="status" aria-live="polite" className="border border-[var(--app-border)] p-3 text-sm">{message}</p>:null}
    <Panel as="section" className="grid gap-5 p-5"><div><h2 className="text-lg font-black">새 캠페인</h2><p className="mt-1 text-sm text-[var(--app-muted)]">HTML은 템플릿에서 고정되며 캠페인 조건만 입력합니다.</p></div><div className="grid gap-4 md:grid-cols-2">
      <label className="grid gap-2 text-sm font-bold">템플릿<select value={campaignType} onChange={event=>{const value=event.target.value as typeof campaignType;setCampaignType(value);setName(value==="promotion"?"HairFit 정식 출시 기존 회원 프로모션":"HairFit 풀 스타일 서비스 개편 안내");setSubject(value==="promotion"?"(광고) HairFit 정식 출시 기념, 기존 회원 무료 풀스타일 1회권":"[HairFit] 풀 스타일 컨설팅 서비스 개편 안내");setPreheader(value==="promotion"?`${LAUNCH_PROMOTION_CODE} 등록 후 30일 안에 무료 풀스타일 상담을 시작하세요.`:"현재 이용권은 그대로 유지되며 상담 결과와 사후관리 경험이 더 구체적으로 바뀝니다.");}} className="min-h-11 border border-[var(--app-border)] bg-[var(--app-surface)] px-3"><option value="promotion">정식 출시 프로모션</option><option value="service_notice">서비스 개편 운영 안내</option></select></label>
      <label className="grid gap-2 text-sm font-bold">캠페인 이름<input value={name} onChange={event=>setName(event.target.value)} className="min-h-11 border border-[var(--app-border)] bg-[var(--app-surface)] px-3"/></label>
      <label className="grid gap-2 text-sm font-bold">기존회원 가입 기준<input type="datetime-local" value={cutoff} onChange={event=>setCutoff(event.target.value)} className="min-h-11 border border-[var(--app-border)] bg-[var(--app-surface)] px-3"/></label>
      <label className="grid gap-2 text-sm font-bold md:col-span-2">메일 제목<input value={subject} maxLength={180} onChange={event=>setSubject(event.target.value)} className="min-h-11 border border-[var(--app-border)] bg-[var(--app-surface)] px-3"/></label>
      <label className="grid gap-2 text-sm font-bold md:col-span-2">프리헤더<input value={preheader} maxLength={240} onChange={event=>setPreheader(event.target.value)} className="min-h-11 border border-[var(--app-border)] bg-[var(--app-surface)] px-3"/></label>
      {campaignType==="promotion"?<><label className="grid gap-2 text-sm font-bold">프로모션 코드<input value={code} onChange={event=>setCode(event.target.value.toUpperCase())} className="min-h-11 border border-[var(--app-border)] bg-[var(--app-surface)] px-3 uppercase"/></label><label className="grid gap-2 text-sm font-bold">코드 등록 시작<input type="datetime-local" value={claimStarts} onChange={event=>setClaimStarts(event.target.value)} className="min-h-11 border border-[var(--app-border)] bg-[var(--app-surface)] px-3"/></label><label className="grid gap-2 text-sm font-bold">코드 등록 종료<input type="datetime-local" value={claimEnds} onChange={event=>setClaimEnds(event.target.value)} className="min-h-11 border border-[var(--app-border)] bg-[var(--app-surface)] px-3"/></label></>:null}
    </div><div className="flex flex-wrap gap-2"><Button variant="secondary" disabled={busy!==null} onClick={()=>void act({action:"preview",campaignType,subject,preheader,promotionCode:code,claimEndsAt:new Date(claimEnds).toISOString()})}>템플릿 미리보기</Button><Button disabled={busy!==null||!payload?.enabled} onClick={()=>void create()}>초안 만들기</Button></div>
    {preview?<SurfaceCard className="grid gap-3 p-4"><div><p className="text-xs font-bold text-[var(--app-muted)]">제목</p><p className="font-black">{preview.subject}</p><p className="mt-1 text-sm">{preview.preheader}</p></div><iframe title="이메일 HTML 미리보기" srcDoc={preview.html} className="h-[480px] w-full border border-[var(--app-border)] bg-white"/><details><summary className="cursor-pointer text-sm font-bold">텍스트 버전</summary><pre className="mt-3 whitespace-pre-wrap text-xs">{preview.text}</pre></details></SurfaceCard>:null}</Panel>
    <Panel as="section" className="grid gap-4 p-5"><div><h2 className="text-lg font-black">캠페인 현황</h2><p className="mt-1 text-sm text-[var(--app-muted)]">프로모션 메일은 수신 동의자만 발송 대상이며 인앱 자격 수와 구분됩니다.</p></div>{payload?.campaigns?.length?payload.campaigns.map(campaign=><SurfaceCard key={campaign.id} className="grid gap-4 p-4"><div className="flex flex-col gap-2 sm:flex-row sm:justify-between"><div><p className="font-black">{campaign.name}</p><p className="mt-1 text-xs text-[var(--app-muted)]">{campaign.status} · 전체 {campaign.counts.total||0} · 이메일 {campaign.counts.emailEligible||0} · 인앱 전용 {campaign.counts.inAppOnly||0}</p><p className="mt-1 text-xs text-[var(--app-muted)]">테스트 {campaign.test_sent_at?"완료":"필요"} · 예약 {campaign.scheduled_at?new Date(campaign.scheduled_at).toLocaleString("ko-KR"):"미정"}</p></div><span className="text-xs font-black">{campaign.campaign_type==="promotion"?campaign.promotion_code:"운영 안내"}</span></div><div className="flex flex-wrap gap-2">{["draft","audience_ready"].includes(campaign.status)?<Button variant="secondary" disabled={busy!==null} onClick={()=>void act({action:"audience",campaignId:campaign.id})}>대상 산정·동결</Button>:null}{campaign.status==="audience_ready"?<><Button variant="secondary" disabled={busy!==null} onClick={()=>void act({action:"test",campaignId:campaign.id})}>관리자 테스트 발송</Button><Button disabled={busy!==null||!campaign.test_sent_at} onClick={()=>{setScheduleTarget(campaign);setConfirmation("");}}>발송 예약</Button></>:null}{["scheduled","sending"].includes(campaign.status)?<Button variant="secondary" onClick={()=>void act({action:"pause",campaignId:campaign.id})}>일시중지</Button>:null}{campaign.status==="paused"?<Button variant="secondary" onClick={()=>void act({action:"resume",campaignId:campaign.id})}>재개</Button>:null}{["scheduled","sending","paused"].includes(campaign.status)?<><Button variant="secondary" onClick={()=>void act({action:"retry",campaignId:campaign.id})}>실패 건 재시도</Button><Button variant="secondary" onClick={()=>void act({action:"cancel",campaignId:campaign.id})}>취소</Button></>:null}</div></SurfaceCard>):<p className="text-sm text-[var(--app-muted)]">생성된 캠페인이 없습니다.</p>}</Panel>
    <ConfirmActionDialog open={Boolean(scheduleTarget)} onOpenChange={open=>{if(!open&&!busy)setScheduleTarget(null);}} onConfirm={()=>{if(scheduleTarget)void act({action:"schedule",campaignId:scheduleTarget.id,scheduledAt:new Date(scheduledAt).toISOString()}).then(ok=>{if(ok)setScheduleTarget(null);});}} title="캠페인 발송 예약" description="동결된 대상과 현재 템플릿으로 예약합니다. 이후 콘텐츠와 대상은 수정할 수 없습니다." confirmLabel="발송 예약" isPending={busy==="schedule"} confirmDisabled={confirmation!=="발송 예약"} target={scheduleTarget?.name} afterValue={scheduledAt} confirmationSlot={<div className="grid gap-3"><label className="grid gap-2 text-sm font-bold">발송 예약 시각<input type="datetime-local" value={scheduledAt} onChange={event=>setScheduledAt(event.target.value)} className="min-h-11 border border-[var(--app-border)] px-3"/></label><label className="grid gap-2 text-sm font-bold">확인을 위해 ‘발송 예약’을 입력하세요<input value={confirmation} onChange={event=>setConfirmation(event.target.value)} className="min-h-11 border border-[var(--app-border)] px-3"/></label></div>}/>
  </main>;
}
