"use client";
import { MAKEUP_MODE_LABELS, type MakeupRationaleNarrativeV1, type MakeupRecommendationRationaleV1 } from "@hairfit/shared/makeup";
import type { CapabilityResult } from "@hairfit/shared/consulting/capability";
import { Button } from "../../ui/Button";
import { Panel, SurfaceCard } from "../workbenches/shared";

export function MakeupRecommendationReview({ rationale, ai, working, onDecision, onRetry, onEdit }: { rationale: MakeupRecommendationRationaleV1; ai?: CapabilityResult<MakeupRationaleNarrativeV1> | null; working?: boolean; onDecision: (decision: "accept_adjustment" | "keep_selection") => void; onRetry?: () => void; onEdit?: () => void }) {
  const narrative = ai?.state === "completed" ? ai.output : null;
  return <div className="grid gap-5"><Panel className="p-6"><p className="app-kicker">Makeup recommendation</p><h2 className="mt-2 text-2xl font-black">내 선택과 AI 조정안을 비교하세요</h2><p className="mt-2 text-sm leading-6 text-[var(--app-muted)]">AI는 선택을 자동 변경하지 않습니다. 검증된 근거를 보고 적용 여부를 직접 확정합니다.</p></Panel>
    <div className="grid gap-4 md:grid-cols-2"><SurfaceCard><p className="app-kicker">사용자 선택</p><h3 className="mt-2 text-xl font-black">{MAKEUP_MODE_LABELS[rationale.requestedMode]}</h3><p className="mt-3 text-sm text-[var(--app-muted)]">원래 선택한 인상과 강도를 그대로 유지합니다.</p></SurfaceCard><SurfaceCard><p className="app-kicker">AI 조정안</p><h3 className="mt-2 text-xl font-black">{MAKEUP_MODE_LABELS[rationale.suggestedMode]}</h3><p className="mt-3 text-sm text-[var(--app-muted)]">{rationale.adjustmentRequired ? rationale.tradeoffs[0] : "현재 조건과 충돌이 없어 같은 방향을 추천합니다."}</p></SurfaceCard></div>
    <Panel className="p-6"><p className="app-kicker">추천 이유</p><div className="mt-4 grid gap-3 md:grid-cols-5">{rationale.evidence.map((item) => <SurfaceCard key={item.id}><p className="text-xs font-black text-[var(--app-muted)]">{item.label}</p><p className="mt-2 font-black">{item.finding}</p><p className="mt-2 text-xs leading-5 text-[var(--app-muted)]">{item.impact}</p></SurfaceCard>)}</div>{narrative ? <div className="mt-5 border-t border-[var(--app-border)] pt-5"><h3 className="font-black">{narrative.headline}</h3><p className="mt-2 text-sm leading-6">{narrative.summary}</p></div> : <p className="mt-5 text-sm text-[var(--app-muted)]" role="status" aria-live="polite">{ai && ["queued", "waiting", "running", "partial"].includes(ai.state) ? "AI가 근거를 읽기 쉬운 문장으로 정리 중입니다. 기다리지 않고 선택할 수 있어요." : "구조화 추천은 준비되었습니다. AI 설명이 없어도 다음 단계로 진행할 수 있어요."}</p>}{ai && ["failed", "retry_required"].includes(ai.state) && onRetry ? <Button className="mt-3" variant="ghost" onClick={onRetry}>AI 설명만 다시 시도</Button> : null}</Panel>
    <Panel className="p-6"><p className="app-kicker">예상 변화와 주의점</p><ul className="mt-3 grid gap-2 text-sm">{[...rationale.tradeoffs, ...rationale.limitations].map((item) => <li key={item}>· {item}</li>)}</ul><div className="mt-6 grid gap-2 sm:grid-cols-2"><Button disabled={working} onClick={() => onDecision("accept_adjustment")}>AI 조정안 적용</Button><Button disabled={working} variant="secondary" onClick={() => onDecision("keep_selection")}>내 선택 유지</Button></div>{onEdit ? <Button className="mt-3" variant="ghost" disabled={working} onClick={onEdit}>인터뷰 답변 수정</Button> : null}</Panel>
  </div>;
}
