"use client";

import type { MakeupContextProfile } from "@hairfit/shared/makeup";
import { Button } from "../../ui/Button";

const PRESENTATIONS: Array<[MakeupContextProfile["presentation"], string]> = [["invisible_correction", "티 나지 않는 보정"], ["natural_grooming", "자연스러운 정돈"], ["defined", "또렷한 인상"], ["expressive", "표현력 있는 메이크업"], ["editorial", "에디토리얼"]];
const OCCASIONS = [["daily", "데일리"], ["work_interview", "업무·면접"], ["date", "데이트"], ["event_guest", "행사 참석"], ["profile_shoot", "프로필 촬영"], ["wedding", "웨딩"], ["stage_content", "무대·콘텐츠"]];

export function MakeupContextForm({ value, onChange, onSubmit, working }: { value: MakeupContextProfile; onChange: (value: MakeupContextProfile) => void; onSubmit: () => void; working: boolean }) {
  const textList = (key: "exclusions" | "ownedProductTypes" | "ownedToolTypes", raw: string) => onChange({ ...value, [key]: raw.split(",").map((item) => item.trim()).filter(Boolean) });
  return <form onSubmit={(event) => { event.preventDefault(); onSubmit(); }} className="grid gap-5">
    <fieldset data-consulting-input-control="true" className="f-consulting-input-control grid gap-3"><legend className="text-sm font-black">원하는 표현</legend><div className="grid gap-2 sm:grid-cols-2">{PRESENTATIONS.map(([id, label]) => <button key={id} type="button" aria-pressed={value.presentation === id} onClick={() => onChange({ ...value, presentation: id })} className={`min-h-11 border px-3 py-2 text-left text-sm font-bold ${value.presentation === id ? "border-[var(--app-border-strong)] bg-[var(--app-inverse)] text-[var(--app-inverse-text)]" : "border-[var(--app-border)]"}`}>{label}</button>)}</div></fieldset>
    <fieldset data-consulting-input-control="true" className="f-consulting-input-control grid gap-3"><legend className="text-sm font-black">사용 상황</legend><div className="flex flex-wrap gap-2">{OCCASIONS.map(([id, label]) => <button key={id} type="button" aria-pressed={value.occasions.includes(id)} onClick={() => onChange({ ...value, occasions: value.occasions.includes(id) ? value.occasions.filter((item) => item !== id) : [...value.occasions, id] })} className={`min-h-11 border px-3 py-2 text-sm font-bold ${value.occasions.includes(id) ? "border-[var(--app-border-strong)] bg-[var(--app-inverse)] text-[var(--app-inverse-text)]" : "border-[var(--app-border)]"}`}>{label}</button>)}</div></fieldset>
    <div className="grid gap-4 sm:grid-cols-2">
      <label data-consulting-input-control="true" className="f-consulting-input-control grid gap-2 text-sm font-black">준비 시간<select className="app-input min-h-11 px-3" value={value.preparationMinutes} onChange={(event) => onChange({ ...value, preparationMinutes: Number(event.target.value) as MakeupContextProfile["preparationMinutes"] })}>{[5, 10, 20, 30].map((minutes) => <option key={minutes} value={minutes}>{minutes}분</option>)}</select></label>
      <label data-consulting-input-control="true" className="f-consulting-input-control grid gap-2 text-sm font-black">숙련도<select className="app-input min-h-11 px-3" value={value.skillLevel} onChange={(event) => onChange({ ...value, skillLevel: event.target.value as MakeupContextProfile["skillLevel"] })}><option value="none">처음</option><option value="basic">기초</option><option value="intermediate">중급</option><option value="advanced">숙련</option></select></label>
      <label data-consulting-input-control="true" className="f-consulting-input-control grid gap-2 text-sm font-black">피부 표현<select className="app-input min-h-11 px-3" value={value.finishPreference} onChange={(event) => onChange({ ...value, finishPreference: event.target.value as MakeupContextProfile["finishPreference"] })}><option value="matte">매트</option><option value="semi_matte">세미 매트</option><option value="natural">내추럴</option><option value="semi_glow">세미 글로우</option><option value="glow">글로우</option></select></label>
      <label data-consulting-input-control="true" className="f-consulting-input-control grid gap-2 text-sm font-black">수염·구레나룻<select className="app-input min-h-11 px-3" value={value.facialHair.type} onChange={(event) => onChange({ ...value, facialHair: { ...value.facialHair, type: event.target.value as MakeupContextProfile["facialHair"]["type"] } })}><option value="none">없음</option><option value="stubble">짧은 수염</option><option value="mustache">콧수염</option><option value="beard">턱수염</option><option value="mixed">혼합</option></select></label>
    </div>
    {value.facialHair.type !== "none" ? <label data-consulting-input-control="true" className="f-consulting-input-control flex min-h-11 items-center gap-3 text-sm font-bold"><input type="checkbox" checked={value.facialHair.userWantsCoverage} onChange={(event) => onChange({ ...value, facialHair: { ...value.facialHair, userWantsCoverage: event.target.checked } })} />수염 주변 색 보정을 원해요</label> : null}
    <label data-consulting-input-control="true" className="f-consulting-input-control grid gap-2 text-sm font-black">피하고 싶은 표현<input className="app-input min-h-11 px-3 font-normal" value={value.exclusions.join(", ")} onChange={(event) => textList("exclusions", event.target.value)} placeholder="두꺼운 베이스, 강한 펄" /></label>
    <label data-consulting-input-control="true" className="f-consulting-input-control grid gap-2 text-sm font-black">보유 제품 종류<input className="app-input min-h-11 px-3 font-normal" value={value.ownedProductTypes.join(", ")} onChange={(event) => textList("ownedProductTypes", event.target.value)} placeholder="쿠션, 립 틴트" /></label>
    <label data-consulting-input-control="true" className="f-consulting-input-control grid gap-2 text-sm font-black">보유 도구<input className="app-input min-h-11 px-3 font-normal" value={value.ownedToolTypes.join(", ")} onChange={(event) => textList("ownedToolTypes", event.target.value)} placeholder="퍼프, 브로우 브러시" /></label>
    <p className="text-xs leading-5 text-[var(--app-muted)]">온보딩 표현 대상은 근거로만 보존되며, 성별 때문에 메이크업 모듈이 차단되지는 않습니다.</p>
    <Button type="submit" loading={working} className="min-h-12">방향 맵 만들기</Button>
  </form>;
}
