import type { LocalizationResource } from "@clerk/types";

export const koreanClerkLocalization = {
  locale: "ko-KR",
  maintenanceMode: "현재 점검 중입니다. 잠시 후 다시 시도해 주세요.",
  socialButtonsBlockButton: "{{provider|titleize}} 계정으로 계속하기",
  socialButtonsBlockButtonManyInView: "{{provider|titleize}}로 계속하기",
  lastAuthenticationStrategy: "마지막으로 사용한 방법",
  dividerText: "또는",
  backButton: "뒤로",
  footerActionLink__useAnotherMethod: "다른 방법 사용",
  footerActionLink__alternativePhoneCodeProvider: "다른 인증 방법 사용",
  footerPageLink__help: "도움말",
  footerPageLink__privacy: "개인정보처리방침",
  footerPageLink__terms: "이용약관",
  paginationButton__previous: "이전",
  paginationButton__next: "다음",
  paginationRowText__displaying: "표시 중",
  paginationRowText__of: "/",

  formFieldLabel__emailAddress: "이메일 주소",
  formFieldLabel__emailAddresses: "이메일 주소",
  formFieldLabel__phoneNumber: "전화번호",
  formFieldLabel__username: "사용자 이름",
  formFieldLabel__emailAddress_username: "이메일 또는 사용자 이름",
  formFieldLabel__password: "비밀번호",
  formFieldLabel__currentPassword: "현재 비밀번호",
  formFieldLabel__newPassword: "새 비밀번호",
  formFieldLabel__confirmPassword: "비밀번호 확인",
  formFieldLabel__signOutOfOtherSessions: "다른 세션에서 로그아웃",
  formFieldLabel__firstName: "이름",
  formFieldLabel__lastName: "성",
  formFieldLabel__backupCode: "백업 코드",
  formFieldLabel__organizationName: "조직 이름",
  formFieldLabel__organizationSlug: "조직 URL",
  formFieldLabel__organizationDomain: "조직 도메인",
  formFieldLabel__role: "역할",
  formFieldLabel__confirmDeletion: "삭제 확인",
  formFieldLabel__passkeyName: "패스키 이름",

  formFieldInputPlaceholder__emailAddress: "이메일 주소를 입력하세요",
  formFieldInputPlaceholder__emailAddresses: "이메일 주소를 입력하세요",
  formFieldInputPlaceholder__phoneNumber: "전화번호를 입력하세요",
  formFieldInputPlaceholder__username: "사용자 이름을 입력하세요",
  formFieldInputPlaceholder__emailAddress_username: "이메일 또는 사용자 이름을 입력하세요",
  formFieldInputPlaceholder__password: "비밀번호를 입력하세요",
  formFieldInputPlaceholder__firstName: "이름을 입력하세요",
  formFieldInputPlaceholder__lastName: "성을 입력하세요",
  formFieldInputPlaceholder__backupCode: "백업 코드를 입력하세요",
  formFieldInputPlaceholder__organizationName: "조직 이름을 입력하세요",
  formFieldInputPlaceholder__organizationSlug: "조직 URL을 입력하세요",
  formFieldInputPlaceholder__confirmDeletionUserAccount: "계정 삭제를 입력하세요",

  formFieldInput__emailAddress_format: "올바른 이메일 주소를 입력하세요.",
  formFieldError__notMatchingPasswords: "비밀번호가 일치하지 않습니다.",
  formFieldError__matchingPasswords: "비밀번호가 일치합니다.",
  formFieldError__verificationLinkExpired: "인증 링크가 만료되었습니다.",
  formFieldAction__forgotPassword: "비밀번호를 잊으셨나요?",
  formFieldHintText__optional: "선택 사항",
  formButtonPrimary: "계속",
  formButtonPrimary__verify: "인증",
  signInEnterPasswordTitle: "비밀번호 입력",

  badge__primary: "기본",
  badge__thisDevice: "현재 기기",
  badge__userDevice: "사용자 기기",
  badge__default: "기본",
  badge__unverified: "미인증",
  badge__requiresAction: "조치 필요",
  badge__you: "나",
  membershipRole__admin: "관리자",
  membershipRole__basicMember: "멤버",
  membershipRole__guestMember: "게스트",

  signIn: {
    start: {
      title: "로그인",
      titleCombined: "계속하려면 로그인하세요",
      subtitle: "HairFit 계정으로 계속하세요.",
      subtitleCombined: "계정에 로그인하거나 새 계정을 만드세요.",
      actionText: "계정이 없으신가요?",
      actionLink: "회원가입",
      actionLink__use_email: "이메일 사용",
      actionLink__use_phone: "전화번호 사용",
      actionLink__use_username: "사용자 이름 사용",
      actionLink__use_email_username: "이메일 또는 사용자 이름 사용",
      actionLink__use_passkey: "패스키 사용",
      actionText__join_waitlist: "아직 이용 권한이 없으신가요?",
      actionLink__join_waitlist: "대기자 명단 참여",
    },
    password: {
      title: "비밀번호 입력",
      subtitle: "{{identifier}} 계정으로 계속합니다.",
      actionLink: "다른 방법 사용",
    },
    passwordPwned: {
      title: "이 비밀번호는 안전하지 않습니다.",
    },
    passwordCompromised: {
      title: "이 비밀번호는 유출된 기록이 있습니다.",
    },
    passkey: {
      title: "패스키로 로그인",
      subtitle: "등록된 패스키를 사용해 계속하세요.",
    },
    forgotPasswordAlternativeMethods: {
      title: "비밀번호 재설정",
      label__alternativeMethods: "다른 방법",
      blockButton__resetPassword: "비밀번호 재설정",
    },
    forgotPassword: {
      title: "비밀번호 재설정",
      subtitle: "계정에 연결된 인증 방법으로 코드를 보내드립니다.",
      subtitle_email: "이메일로 전송된 코드를 입력하세요.",
      subtitle_phone: "전화번호로 전송된 코드를 입력하세요.",
      formTitle: "재설정 코드",
      resendButton: "코드 다시 보내기",
    },
    resetPassword: {
      title: "새 비밀번호 설정",
      formButtonPrimary: "비밀번호 변경",
      successMessage: "비밀번호가 변경되었습니다.",
      requiredMessage: "새 비밀번호를 입력하세요.",
    },
    emailCode: {
      title: "이메일 확인",
      subtitle: "{{identifier}}로 전송된 코드를 입력하세요.",
      formTitle: "인증 코드",
      resendButton: "코드 다시 보내기",
    },
    emailLink: {
      title: "이메일 링크 확인",
      subtitle: "{{identifier}}로 보낸 링크를 확인하세요.",
      formTitle: "인증 링크를 보냈습니다.",
      formSubtitle: "메일함에서 로그인 링크를 열어 주세요.",
      resendButton: "링크 다시 보내기",
      verified: {
        title: "인증되었습니다.",
        subtitle: "잠시만 기다려 주세요.",
      },
      loading: {
        title: "인증 중입니다.",
        subtitle: "잠시만 기다려 주세요.",
      },
      failed: {
        title: "인증에 실패했습니다.",
        subtitle: "링크가 유효하지 않거나 만료되었습니다.",
      },
      expired: {
        title: "링크가 만료되었습니다.",
        subtitle: "새 인증 링크를 요청해 주세요.",
      },
    },
    phoneCode: {
      title: "전화번호 확인",
      subtitle: "{{identifier}}로 전송된 코드를 입력하세요.",
      formTitle: "인증 코드",
      resendButton: "코드 다시 보내기",
    },
    alternativeMethods: {
      title: "다른 로그인 방법",
      subtitle: "계속할 방법을 선택하세요.",
      actionText: "다시 로그인으로 돌아가시겠어요?",
      actionLink: "돌아가기",
      blockButton__emailLink: "{{identifier}}로 이메일 링크 받기",
      blockButton__emailCode: "{{identifier}}로 이메일 코드 받기",
      blockButton__phoneCode: "{{identifier}}로 SMS 코드 받기",
      blockButton__password: "비밀번호로 계속하기",
      blockButton__passkey: "패스키로 계속하기",
      blockButton__totp: "인증 앱 코드 사용",
      blockButton__backupCode: "백업 코드 사용",
      getHelp: {
        title: "도움이 필요하신가요?",
        content: "로그인할 수 없다면 지원팀에 문의해 주세요.",
        blockButton__emailSupport: "지원팀에 이메일 보내기",
      },
    },
    noAvailableMethods: {
      title: "사용 가능한 로그인 방법이 없습니다.",
      subtitle: "다른 계정으로 시도하거나 지원팀에 문의해 주세요.",
      message: "현재 이 계정에서 사용할 수 있는 인증 방법이 없습니다.",
    },
    accountSwitcher: {
      title: "계정 선택",
      subtitle: "계속할 계정을 선택하세요.",
      action__addAccount: "계정 추가",
      action__signOutAll: "모든 계정 로그아웃",
    },
  },

  signUp: {
    start: {
      title: "회원가입",
      titleCombined: "계정을 만들거나 로그인하세요",
      subtitle: "HairFit 계정을 만들어 시작하세요.",
      subtitleCombined: "계정을 만들거나 기존 계정으로 로그인하세요.",
      actionText: "이미 계정이 있으신가요?",
      actionLink: "로그인",
      actionLink__use_phone: "전화번호 사용",
      actionLink__use_email: "이메일 사용",
    },
    continue: {
      title: "계정 정보 입력",
      subtitle: "가입을 완료하려면 필요한 정보를 입력하세요.",
      actionText: "이미 계정이 있으신가요?",
      actionLink: "로그인",
    },
    emailCode: {
      title: "이메일 확인",
      subtitle: "이메일로 전송된 코드를 입력하세요.",
      formTitle: "인증 코드",
      formSubtitle: "{{identifier}}로 전송된 코드를 입력하세요.",
      resendButton: "코드 다시 보내기",
    },
    emailLink: {
      title: "이메일 확인",
      subtitle: "{{identifier}}로 보낸 링크를 확인하세요.",
      formTitle: "인증 링크를 보냈습니다.",
      formSubtitle: "메일함에서 인증 링크를 열어 주세요.",
      resendButton: "링크 다시 보내기",
      verified: {
        title: "인증되었습니다.",
      },
      loading: {
        title: "인증 중입니다.",
      },
    },
    phoneCode: {
      title: "전화번호 확인",
      subtitle: "전화번호로 전송된 코드를 입력하세요.",
      formTitle: "인증 코드",
      formSubtitle: "{{identifier}}로 전송된 코드를 입력하세요.",
      resendButton: "코드 다시 보내기",
    },
    restrictedAccess: {
      title: "접근할 수 없습니다.",
      subtitle: "이 애플리케이션에 가입할 수 있는 권한이 없습니다.",
      subtitleWaitlist: "현재 대기자 명단을 운영 중입니다.",
      actionText: "이미 계정이 있으신가요?",
      actionLink: "로그인",
      blockButton__emailSupport: "지원팀에 문의",
      blockButton__joinWaitlist: "대기자 명단 참여",
    },
    legalConsent: {
      continue: {
        title: "약관 동의",
        subtitle: "계속하려면 약관에 동의해 주세요.",
      },
      checkbox: {
        label__termsOfServiceAndPrivacyPolicy:
          "{{termsOfServiceLink}} 및 {{privacyPolicyLink}}에 동의합니다.",
        label__onlyPrivacyPolicy: "{{privacyPolicyLink}}에 동의합니다.",
        label__onlyTermsOfService: "{{termsOfServiceLink}}에 동의합니다.",
      },
    },
  },

  reverification: {
    password: {
      title: "비밀번호 재확인",
      subtitle: "보안을 위해 비밀번호를 다시 입력하세요.",
      actionLink: "다른 방법 사용",
    },
    emailCode: {
      title: "이메일 재확인",
      subtitle: "{{identifier}}로 전송된 코드를 입력하세요.",
      formTitle: "인증 코드",
      resendButton: "코드 다시 보내기",
    },
    phoneCode: {
      title: "전화번호 재확인",
      subtitle: "{{identifier}}로 전송된 코드를 입력하세요.",
      formTitle: "인증 코드",
      resendButton: "코드 다시 보내기",
    },
    alternativeMethods: {
      title: "다른 인증 방법",
      subtitle: "계속할 인증 방법을 선택하세요.",
      actionText: "이전 화면으로 돌아가시겠어요?",
      actionLink: "돌아가기",
      blockButton__emailCode: "{{identifier}}로 이메일 코드 받기",
      blockButton__phoneCode: "{{identifier}}로 SMS 코드 받기",
      blockButton__password: "비밀번호 사용",
      blockButton__totp: "인증 앱 코드 사용",
      blockButton__passkey: "패스키 사용",
      blockButton__backupCode: "백업 코드 사용",
      getHelp: {
        title: "도움이 필요하신가요?",
        content: "계정 인증에 문제가 있다면 지원팀에 문의해 주세요.",
        blockButton__emailSupport: "지원팀에 이메일 보내기",
      },
    },
  },

  userButton: {
    action__manageAccount: "계정 관리",
    action__signOut: "로그아웃",
    action__signOutAll: "모든 계정 로그아웃",
    action__addAccount: "계정 추가",
    action__openUserMenu: "사용자 메뉴 열기",
    action__closeUserMenu: "사용자 메뉴 닫기",
  },

  userProfile: {
    mobileButton__menu: "메뉴",
    formButtonPrimary__continue: "계속",
    formButtonPrimary__save: "저장",
    formButtonPrimary__finish: "완료",
    formButtonPrimary__remove: "삭제",
    formButtonPrimary__add: "추가",
    formButtonReset: "취소",
    navbar: {
      title: "계정",
      description: "계정 정보와 보안 설정을 관리하세요.",
      account: "프로필",
      security: "보안",
      billing: "결제",
      apiKeys: "API 키",
    },
    start: {
      headerTitle__account: "계정",
      headerTitle__security: "보안",
      profileSection: {
        title: "프로필",
        primaryButton: "프로필 수정",
      },
      usernameSection: {
        title: "사용자 이름",
        primaryButton__updateUsername: "사용자 이름 변경",
        primaryButton__setUsername: "사용자 이름 설정",
      },
      emailAddressesSection: {
        title: "이메일 주소",
        primaryButton: "이메일 추가",
        detailsAction__primary: "기본 이메일",
        detailsAction__nonPrimary: "기본으로 설정",
        detailsAction__unverified: "인증",
        destructiveAction: "삭제",
      },
      phoneNumbersSection: {
        title: "전화번호",
        primaryButton: "전화번호 추가",
        detailsAction__primary: "기본 전화번호",
        detailsAction__nonPrimary: "기본으로 설정",
        detailsAction__unverified: "인증",
        destructiveAction: "삭제",
      },
      connectedAccountsSection: {
        title: "연결된 계정",
        primaryButton: "계정 연결",
        actionLabel__connectionFailed: "다시 연결 필요",
        actionLabel__reauthorize: "다시 인증",
        subtitle__reauthorize: "계정을 다시 인증해 주세요.",
        subtitle__disconnected: "연결이 해제되었습니다.",
        destructiveActionTitle: "연결 해제",
      },
      enterpriseAccountsSection: {
        title: "엔터프라이즈 계정",
      },
      passwordSection: {
        title: "비밀번호",
        primaryButton__updatePassword: "비밀번호 변경",
        primaryButton__setPassword: "비밀번호 설정",
      },
      passkeysSection: {
        title: "패스키",
        primaryButton: "패스키 추가",
        menuAction__rename: "이름 변경",
        menuAction__destructive: "삭제",
      },
      mfaSection: {
        title: "2단계 인증",
        primaryButton: "2단계 인증 추가",
        phoneCode: {
          destructiveActionLabel: "삭제",
          actionLabel__setDefault: "기본으로 설정",
        },
        backupCodes: {
          headerTitle: "백업 코드",
          title__regenerate: "백업 코드 재생성",
          subtitle__regenerate: "새 코드를 만들면 기존 코드는 사용할 수 없습니다.",
          actionLabel__regenerate: "재생성",
        },
        totp: {
          headerTitle: "인증 앱",
          destructiveActionTitle: "인증 앱 제거",
        },
      },
      activeDevicesSection: {
        title: "활성 기기",
        destructiveAction: "로그아웃",
      },
      dangerSection: {
        title: "위험 구역",
        deleteAccountButton: "계정 삭제",
      },
    },
    profilePage: {
      title: "프로필 수정",
      imageFormTitle: "프로필 이미지",
      imageFormSubtitle: "권장 크기: 정사각형 이미지",
      imageFormDestructiveActionSubtitle: "현재 프로필 이미지를 제거합니다.",
      fileDropAreaHint: "이미지를 끌어오거나 클릭해 업로드하세요.",
      readonly: "이 정보는 수정할 수 없습니다.",
      successMessage: "프로필이 저장되었습니다.",
    },
    usernamePage: {
      successMessage: "사용자 이름이 저장되었습니다.",
      title__set: "사용자 이름 설정",
      title__update: "사용자 이름 변경",
    },
    emailAddressPage: {
      title: "이메일 주소 추가",
      verifyTitle: "이메일 인증",
      formHint: "인증 코드를 입력해 이메일을 확인하세요.",
      emailCode: {
        formHint: "인증 코드를 입력해 이메일을 확인하세요.",
        formTitle: "인증 코드",
        formSubtitle: "{{identifier}}로 전송된 코드를 입력하세요.",
        resendButton: "코드 다시 보내기",
        successMessage: "이메일 주소가 인증되었습니다.",
      },
      removeResource: {
        title: "이메일 주소 삭제",
        messageLine1: "{{identifier}} 이메일 주소를 삭제합니다.",
        messageLine2: "삭제 후에는 이 이메일로 로그인할 수 없습니다.",
        successMessage: "{{emailAddress}} 이메일 주소가 삭제되었습니다.",
      },
    },
    phoneNumberPage: {
      title: "전화번호 추가",
      verifyTitle: "전화번호 인증",
      verifySubtitle: "{{identifier}}로 전송된 코드를 입력하세요.",
      successMessage: "전화번호가 저장되었습니다.",
      infoText: "인증 가능한 전화번호를 입력하세요.",
      removeResource: {
        title: "전화번호 삭제",
        messageLine1: "{{identifier}} 전화번호를 삭제합니다.",
        messageLine2: "삭제 후에는 이 번호로 로그인할 수 없습니다.",
        successMessage: "{{phoneNumber}} 전화번호가 삭제되었습니다.",
      },
    },
    passwordPage: {
      successMessage__set: "비밀번호가 설정되었습니다.",
      successMessage__update: "비밀번호가 변경되었습니다.",
      successMessage__signOutOfOtherSessions: "다른 세션에서 로그아웃되었습니다.",
      checkboxInfoText__signOutOfOtherSessions: "현재 기기를 제외한 모든 기기에서 로그아웃합니다.",
      readonly: "이 비밀번호는 수정할 수 없습니다.",
      title__set: "비밀번호 설정",
      title__update: "비밀번호 변경",
    },
    mfaPage: {
      title: "2단계 인증 추가",
      formHint: "계정 보안을 강화할 인증 방법을 선택하세요.",
    },
    mfaTOTPPage: {
      title: "인증 앱 설정",
      verifyTitle: "인증 코드 입력",
      verifySubtitle: "인증 앱에 표시된 코드를 입력하세요.",
      successMessage: "인증 앱이 설정되었습니다.",
      authenticatorApp: {
        infoText__ableToScan: "인증 앱으로 QR 코드를 스캔하세요.",
        infoText__unableToScan: "QR 코드를 스캔할 수 없다면 아래 키를 입력하세요.",
        inputLabel__unableToScan1: "수동 입력 키",
        inputLabel__unableToScan2: "인증 앱에 입력하세요.",
        buttonAbleToScan__nonPrimary: "QR 코드 스캔",
        buttonUnableToScan__nonPrimary: "수동 입력",
      },
      removeResource: {
        title: "인증 앱 제거",
        messageLine1: "이 인증 방법을 제거합니다.",
        messageLine2: "계정 보안 수준이 낮아질 수 있습니다.",
        successMessage: "인증 앱이 제거되었습니다.",
      },
    },
    backupCodePage: {
      title: "백업 코드",
      title__codelist: "백업 코드 보관",
      subtitle__codelist: "각 코드는 한 번만 사용할 수 있습니다.",
      infoText1: "이 코드를 안전한 곳에 보관하세요.",
      infoText2: "인증 앱이나 휴대폰을 사용할 수 없을 때 필요합니다.",
      successSubtitle: "백업 코드가 생성되었습니다.",
      successMessage: "백업 코드를 저장해 주세요.",
      actionLabel__copy: "복사",
      actionLabel__copied: "복사됨",
      actionLabel__download: "다운로드",
      actionLabel__print: "인쇄",
    },
    deletePage: {
      title: "계정 삭제",
      messageLine1: "계정을 삭제하면 모든 데이터가 영구적으로 제거됩니다.",
      messageLine2: "이 작업은 되돌릴 수 없습니다.",
      actionDescription: "계정 삭제를 확인하려면 아래 문구를 입력하세요.",
      confirm: "계정 삭제",
    },
  },

  unstable__errors: {
    avatar_file_type_invalid: "지원하지 않는 이미지 형식입니다.",
    avatar_file_size_exceeded: "이미지 파일 크기가 너무 큽니다.",
    external_account_not_found: "연결된 계정을 찾을 수 없습니다.",
    identification_deletion_failed: "삭제에 실패했습니다. 잠시 후 다시 시도해 주세요.",
    phone_number_exists: "이미 사용 중인 전화번호입니다.",
    form_identifier_not_found: "계정을 찾을 수 없습니다.",
    captcha_unavailable: "보안 확인을 사용할 수 없습니다.",
    captcha_invalid: "보안 확인에 실패했습니다.",
    passkey_not_supported: "이 브라우저에서는 패스키를 지원하지 않습니다.",
    passkey_retrieval_cancelled: "패스키 인증이 취소되었습니다.",
    passkey_registration_cancelled: "패스키 등록이 취소되었습니다.",
    passkey_already_exists: "이미 등록된 패스키입니다.",
    form_password_pwned: "이 비밀번호는 유출된 기록이 있어 사용할 수 없습니다.",
    form_password_pwned__sign_in: "이 비밀번호는 안전하지 않습니다. 비밀번호를 변경해 주세요.",
    form_new_password_matches_current: "새 비밀번호가 현재 비밀번호와 같습니다.",
    form_password_compromised__sign_in: "이 비밀번호는 유출된 기록이 있습니다. 비밀번호를 변경해 주세요.",
    form_username_invalid_length: "사용자 이름은 {{min_length}}자 이상 {{max_length}}자 이하여야 합니다.",
    form_username_needs_non_number_char: "사용자 이름에는 숫자가 아닌 문자가 포함되어야 합니다.",
    form_username_invalid_character: "사용자 이름에 사용할 수 없는 문자가 포함되어 있습니다.",
    form_param_format_invalid: "입력 형식이 올바르지 않습니다.",
    form_param_format_invalid__email_address: "올바른 이메일 주소를 입력하세요.",
    form_param_type_invalid: "입력값이 올바르지 않습니다.",
    form_param_type_invalid__phone_number: "올바른 전화번호를 입력하세요.",
    form_param_type_invalid__email_address: "올바른 이메일 주소를 입력하세요.",
    form_email_address_blocked: "이 이메일 주소는 사용할 수 없습니다.",
    form_password_length_too_short: "비밀번호가 너무 짧습니다.",
    form_param_nil: "필수 항목을 입력하세요.",
    form_code_incorrect: "인증 코드가 올바르지 않습니다.",
    form_password_incorrect: "비밀번호가 올바르지 않습니다.",
    form_password_or_identifier_incorrect: "계정 정보 또는 비밀번호가 올바르지 않습니다.",
    form_password_validation_failed: "비밀번호 조건을 충족하지 않습니다.",
    not_allowed_access: "접근 권한이 없습니다.",
    form_identifier_exists: "이미 사용 중인 계정 정보입니다.",
    form_identifier_exists__email_address: "이미 사용 중인 이메일 주소입니다.",
    form_identifier_exists__username: "이미 사용 중인 사용자 이름입니다.",
    form_identifier_exists__phone_number: "이미 사용 중인 전화번호입니다.",
    form_password_not_strong_enough: "비밀번호가 충분히 강하지 않습니다.",
    form_password_size_in_bytes_exceeded: "비밀번호가 너무 깁니다.",
    form_param_value_invalid: "입력값이 올바르지 않습니다.",
    passwordComplexity: {
      sentencePrefix: "비밀번호는 다음 조건을 충족해야 합니다.",
      minimumLength: "최소 길이",
      maximumLength: "최대 길이",
      requireNumbers: "숫자 포함",
      requireLowercase: "소문자 포함",
      requireUppercase: "대문자 포함",
      requireSpecialCharacter: "특수문자 포함",
    },
    session_exists: "이미 로그인되어 있습니다.",
  },

  dates: {
    previous6Days: "지난 {{date}}",
    lastDay: "어제",
    sameDay: "오늘",
    nextDay: "내일",
    next6Days: "{{date}}",
    numeric: "{{date}}",
  },
} satisfies LocalizationResource;
