export const PREMIUM_OFFER_POLICY = {
  version: "2026-08-21",
  statusLabel: "출시 예정가",
  disclosure:
    "세 플랜은 같은 공동 혜택 계약을 사용합니다. 표시된 가격은 출시 예정가이며, 새 결제 상품이 연결되기 전에는 이 화면에서 결제되지 않습니다.",
  commonBenefits: [
    "사진 품질·얼굴 구조·추정 퍼스널 컬러 분석",
    "헤어 후보 9개와 패션 방향 9개 룩",
    "후보 비교·최종 결정·Salon Brief",
    "Aftercare와 Style Dossier",
  ],
  offers: [
    {
      key: "private-hair-direction",
      name: "Private Hair Direction",
      koreanName: "프라이빗 헤어 디렉팅",
      priceKrw: 99_000,
      priceLabel: "99,000원",
      periodLabel: "/ 1회",
      tagline: "지금 필요한 한 번의 결정을 선명하게.",
      summary: "공동 혜택 계약을 한 번에 완결하는 단회 플랜",
      management: [
        "공동 혜택 계약으로 컨설팅 1회 완결",
        "결정 시점의 결과와 실행 기준 정리",
        "새 변화가 필요하면 별도 컨설팅으로 다시 시작",
      ],
      ctaLabel: "1회 컨설팅 시작",
      recommended: false,
      planTypeLabel: "1회 완결형",
    },
    {
      key: "total-image-direction",
      name: "Total Image Direction",
      koreanName: "토털 이미지 디렉팅",
      priceKrw: 189_000,
      priceLabel: "189,000원",
      periodLabel: "/ 3개월",
      tagline: "3개월 동안, 같은 스타일 기준과 결과 맥락을 이어갑니다.",
      summary: "공동 혜택 계약을 3개월 동안 유지하는 권장 플랜",
      management: [
        "공동 혜택 계약을 3개월 동안 유지",
        "시술·생활 변화 기록을 같은 결과에 연결",
        "기간 내 결과와 결정 맥락을 이어서 확인",
      ],
      ctaLabel: "3개월 관리 상담 시작",
      recommended: true,
      planTypeLabel: "3개월 관리형",
    },
    {
      key: "signature-style-membership",
      name: "Signature Style Membership",
      koreanName: "시그니처 스타일 멤버십",
      priceKrw: 649_000,
      priceLabel: "649,000원",
      periodLabel: "/ 년",
      tagline: "1년 동안, 나만의 스타일 기준과 선택 이력을 축적합니다.",
      summary: "공동 혜택 계약과 변화 이력을 1년 동안 유지하는 연간 플랜",
      management: [
        "공동 혜택 계약을 1년 동안 유지",
        "시술·생활 변화 기록을 같은 기준에 누적",
        "선택 이력·Before/After·Style Archive 누적",
      ],
      ctaLabel: "연간 멤버십 상담 시작",
      recommended: false,
      planTypeLabel: "연간 관리형",
    },
  ],
} as const;

export type PremiumOffer = (typeof PREMIUM_OFFER_POLICY.offers)[number];
