"use client";

import { useCallback,useEffect,useState } from "react";
import type { AftercareCheckinListV1,AftercareCheckinV1 } from "@hairfit/shared/v2";
import { Button } from "../../ui/Button";
import { SurfaceCard } from "./shared";

const label:Record<AftercareCheckinV1["state"],string>={locked:"예정일 대기",available:"작성 가능",preparing:"답변 준비 중",ready:"답변 완료",failed:"다시 시도 가능"};

export function AftercareCheckinPanel({consultationId,actualServiceId}:{consultationId:string;actualServiceId:string}){
  const [list,setList]=useState<AftercareCheckinListV1|null>(null);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState<number|null>(null);
  const [drafts,setDrafts]=useState<Record<number,{concern:string;satisfaction:number;file:File|null;consent:boolean}>>({});
  const load=useCallback(async()=>{const response=await fetch(`/api/v2/consultations/${encodeURIComponent(consultationId)}/aftercare-checkins`,{cache:"no-store"});const data=await response.json().catch(()=>({})) as AftercareCheckinListV1&{error?:string};if(response.status===404)return;if(!response.ok)throw new Error(data.error||"사후상담 일정을 불러오지 못했습니다.");setList(data);setDrafts((current)=>Object.fromEntries(data.checkins.map((item)=>[item.slot,current[item.slot]??{concern:item.concern,satisfaction:item.satisfaction??3,file:null,consent:false}])));},[consultationId]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load().catch((cause)=>setError(cause instanceof Error?cause.message:"사후상담 일정을 불러오지 못했습니다.")),0);return()=>window.clearTimeout(timer);},[load,actualServiceId]);
  useEffect(()=>{if(!list?.checkins.some((item)=>item.state==="preparing"))return;const timer=window.setInterval(()=>void load(),4000);return()=>window.clearInterval(timer);},[list,load]);
  if(!list)return null;
  const submit=async(item:AftercareCheckinV1)=>{const draft=drafts[item.slot];if(!draft?.concern.trim()||!draft.file||!draft.consent){setError("현재 고민, 사진, 사진 사용 동의를 모두 확인해 주세요.");return;}setBusy(item.slot);setError(null);try{const form=new FormData();form.append("concern",draft.concern);form.append("satisfaction",String(draft.satisfaction));form.append("file",draft.file);form.append("consent","true");const saved=await fetch(`/api/v2/consultations/${encodeURIComponent(consultationId)}/aftercare-checkins/${item.slot}`,{method:"PUT",body:form});const savedData=await saved.json().catch(()=>({})) as {error?:string};if(!saved.ok)throw new Error(savedData.error||"입력을 저장하지 못했습니다.");const submitted=await fetch(`/api/v2/consultations/${encodeURIComponent(consultationId)}/aftercare-checkins/${item.slot}/submit`,{method:"POST",headers:{"Idempotency-Key":`${consultationId}:aftercare-checkin:${item.slot}:${item.scheduledFor}`}});const submitData=await submitted.json().catch(()=>({})) as {error?:string};if(!submitted.ok)throw new Error(submitData.error||"관리 답변을 준비하지 못했습니다.");await load();}catch(cause){setError(cause instanceof Error?cause.message:"관리 답변을 준비하지 못했습니다.");await load().catch(()=>undefined);}finally{setBusy(null);}};
  return <SurfaceCard className="grid gap-5 p-5 sm:p-6"><div><p className="app-kicker">시술 후 AI 사후상담</p><h3 className="mt-2 text-xl font-black">실제 시술일에 맞춰 상태를 확인하세요</h3><p className="mt-2 text-sm leading-6 text-[var(--app-muted)]">사진과 지금의 고민을 함께 남기면 눈에 보이는 변화와 실제 시술 내용을 기준으로 관리 방법을 안내합니다.</p><p className="mt-2 text-sm font-black">총 {list.limit}회 · 완료 {list.used}회 · 남음 {list.remaining}회</p></div>
    {list.revoked?<p role="alert" className="border border-[var(--app-danger)] bg-[var(--app-danger-bg)] p-3 text-sm">환불로 회수된 미사용 사후상담은 이용할 수 없습니다. 이미 완료한 답변은 계속 볼 수 있습니다.</p>:null}
    <div className="grid gap-4">{list.checkins.map((item)=>{const draft=drafts[item.slot]??{concern:item.concern,satisfaction:item.satisfaction??3,file:null,consent:false};const editable=item.state==="available"||item.state==="failed";return <section key={item.id} className="grid gap-4 border border-[var(--app-border)] p-4" aria-labelledby={`aftercare-${item.slot}`}><div className="flex flex-wrap items-center justify-between gap-2"><div><h4 id={`aftercare-${item.slot}`} className="font-black">D+{item.offsetDays} 사후상담</h4><p className="text-xs text-[var(--app-muted)]">{new Date(`${item.scheduledFor}T00:00:00`).toLocaleDateString("ko-KR")}부터 이용</p></div><span className="border border-[var(--app-border)] px-2 py-1 text-xs font-black">{label[item.state]}</span></div>
      {item.response?<div className="grid gap-3 text-sm leading-6"><strong>{item.response.title}</strong><p>{item.response.summary}</p><ul className="grid gap-1">{item.response.careActions.map((action)=><li key={action}>· {action}</li>)}</ul>{item.response.cautions.length?<div><strong>주의해서 볼 점</strong><ul>{item.response.cautions.map((value)=><li key={value}>· {value}</li>)}</ul></div>:null}<p className="font-bold">다음 행동 · {item.response.nextAction}</p><p className="border-t border-[var(--app-border)] pt-3 text-xs text-[var(--app-muted)]">{item.response.safetyNotice}</p></div>:editable?<div className="grid gap-4"><label className="grid gap-2 text-sm font-black">지금 가장 고민되는 점<textarea value={draft.concern} onChange={(event)=>setDrafts((current)=>({...current,[item.slot]:{...draft,concern:event.target.value}}))} className="app-input min-h-24 p-3 font-normal" maxLength={2000}/></label><label className="grid gap-2 text-sm font-black">현재 만족도 · {draft.satisfaction}/5<input type="range" min="1" max="5" value={draft.satisfaction} onChange={(event)=>setDrafts((current)=>({...current,[item.slot]:{...draft,satisfaction:Number(event.target.value)}}))}/></label><label className="grid gap-2 text-sm font-black">현재 헤어 사진<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event)=>setDrafts((current)=>({...current,[item.slot]:{...draft,file:event.target.files?.[0]??null,consent:false}}))} className="app-input min-h-11 px-3 py-2 font-normal"/></label>{draft.file?<label className="flex items-start gap-3 border border-[var(--app-border)] p-3 text-sm"><input type="checkbox" checked={draft.consent} onChange={(event)=>setDrafts((current)=>({...current,[item.slot]:{...draft,consent:event.target.checked}}))} className="mt-1"/><span><strong className="block">사진 분석과 비공개 저장에 동의</strong><span className="mt-1 block text-xs leading-5 text-[var(--app-muted)]">사진은 이 사후상담의 상태 확인에만 사용하며, 답변에는 개인을 식별하지 않는 관찰 내용만 전달합니다.</span></span></label>:null}<Button type="button" loading={busy===item.slot} disabled={!draft.concern.trim()||!draft.file||!draft.consent||list.revoked} onClick={()=>void submit(item)}>사진과 고민으로 관리 답변 받기</Button>{item.state==="failed"?<p className="text-xs text-[var(--app-danger)]">이전 준비가 완료되지 않았습니다. 다시 시도해도 남은 횟수는 줄지 않습니다.</p>:null}</div>:<p className="text-sm text-[var(--app-muted)]">예정일부터 사진과 고민을 남길 수 있습니다.</p>}</section>;})}</div>
    {error?<p role="alert" className="border border-[var(--app-danger)] bg-[var(--app-danger-bg)] p-3 text-sm">{error}</p>:null}
  </SurfaceCard>;
}
