"use client";

import { useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import type { ConsultationPatch, ConsultationSnapshot, PhotoSnapshot } from "../../../lib/consulting/contracts";
import { Panel, SaveStageButton, SurfaceCard, WorkbenchGrid } from "./shared";
import { ConsultationPhotoEvidence } from "../photo/ConsultationPhotoEvidence";

export function PhotoWorkbench({ snapshot, mutate, saving }: { snapshot: ConsultationSnapshot; mutate: (patch: Omit<ConsultationPatch, "expectedVersion">) => Promise<unknown>; saving: boolean }) {
  const searchParams = useSearchParams();
  const returnedGenerationId = searchParams.get("generationId")?.trim() || null;
  const [photo, setPhoto] = useState<PhotoSnapshot>(() => returnedGenerationId ? { ...snapshot.photo, generationId: returnedGenerationId, capturedAt: new Date().toISOString() } : snapshot.photo);
  const allReviewed = photo.quality.every((item) => item.status !== "pending");
  return <WorkbenchGrid><Panel className="grid gap-6 p-5 sm:p-7">
    <div><p className="text-sm font-black">기존 generation 사진 연결</p><p className="mt-1 text-sm text-[var(--app-muted)]">현재 업로드·결제·generation workflow는 호환 경로로 재사용합니다.</p><div className="mt-3 flex flex-wrap gap-2"><input value={photo.generationId ?? ""} onChange={(event) => setPhoto({ ...photo, generationId: event.target.value.trim() || null, capturedAt: new Date().toISOString() })} className="app-input min-h-11 flex-1 px-3" placeholder="generation ID" /><Link href={`/workspace?legacy=1&returnTo=${encodeURIComponent(`/consulting/${snapshot.sessionId}/photo`)}`} className="inline-flex min-h-11 items-center border border-[var(--app-border)] bg-[var(--app-surface)] px-4 text-sm font-black">사진 업로드 열기</Link></div></div>
    <div className="grid gap-2 sm:grid-cols-2">{photo.quality.map((item) => <button key={item.id} type="button" onClick={() => setPhoto({ ...photo, quality: photo.quality.map((entry) => entry.id === item.id ? { ...entry, status: entry.status === "pass" ? "warning" : "pass", message: entry.status === "pass" ? "보완 필요" : "확인 완료" } : entry) })} aria-pressed={item.status === "pass"} className={`grid min-h-20 gap-1 border p-3 text-left ${item.status === "pass" ? "border-[var(--app-success)] bg-[var(--app-success-bg)]" : item.status === "warning" ? "border-[var(--app-warning)] bg-[var(--app-warning-bg)]" : "border-[var(--app-border)] bg-[var(--app-surface)]"}`}><span className="text-sm font-black">{item.label}</span><span className="text-xs text-[var(--app-muted)]">{item.message}</span></button>)}</div>
    <fieldset><legend className="text-sm font-black">사진 사용 범위</legend><div className="mt-2 flex flex-wrap gap-2">{[["analysis","얼굴 분석"],["preview","헤어 프리뷰"],["personalColor","컬러 진단"]].map(([scope,label]) => <button type="button" key={scope} onClick={() => setPhoto({ ...photo, usageScopes: photo.usageScopes.includes(scope) ? photo.usageScopes.filter((item) => item !== scope) : [...photo.usageScopes, scope] })} aria-pressed={photo.usageScopes.includes(scope)} className={`min-h-11 border px-4 text-sm font-black ${photo.usageScopes.includes(scope) ? "bg-[var(--app-inverse)] text-[var(--app-inverse-text)]" : "bg-[var(--app-surface)]"}`}>{label}</button>)}</div><Link href={`/personal-color?source=upload&returnTo=${encodeURIComponent(`/consulting/${snapshot.sessionId}/photo`)}`} className="mt-3 inline-flex min-h-11 items-center border border-[var(--app-border)] px-4 text-sm font-black">컬러 보조 사진·퍼스널 컬러 열기</Link></fieldset>
    <fieldset><legend className="text-sm font-black">사진 보존 기간</legend><div className="mt-2 flex gap-2">{([1,7,30] as const).map((days) => <button type="button" key={days} onClick={() => setPhoto({ ...photo, retentionDays: days })} aria-pressed={photo.retentionDays === days} className={`min-h-11 border px-4 text-sm font-black ${photo.retentionDays === days ? "bg-[var(--app-inverse)] text-[var(--app-inverse-text)]" : "bg-[var(--app-surface)]"}`}>{days}일</button>)}</div></fieldset>
    <SaveStageButton loading={saving} disabled={!photo.generationId || !allReviewed || !photo.usageScopes.length} onClick={() => void mutate({ photo, completeStage: "photo", currentStage: "scan" })} />
  </Panel><div className="grid gap-4"><ConsultationPhotoEvidence sessionId={snapshot.sessionId} enabled={Boolean(snapshot.photo.generationId && snapshot.photo.usageScopes.includes("analysis"))} /><SurfaceCard className="p-5"><p className="app-kicker">PhotoSnapshot</p><h2 className="mt-3 text-xl font-black">분석용 사진과 컬러 보조 사진을 구분합니다</h2><p className="mt-3 text-sm leading-6 text-[var(--app-muted)]">얼굴 원본은 살롱 브리프 공유에 기본 포함되지 않습니다. signed URL이 만료되면 서버에서 다시 발급받습니다.</p></SurfaceCard></div></WorkbenchGrid>;
}
