import type { DiscoveryEvidenceEntry } from "./types.ts";

export const discoveryEvidenceRegistry = [
  {
    id: "EVD-STRATEGY-3",
    status: "verified",
    statement: "HairFit의 현재 프리미엄 컨설팅은 BALANCE, IMAGE, LIFESTYLE 세 전략 방향을 사용한다.",
    sourceRef: "my-app/components/home/PremiumConsultingShowcases.tsx#StrategicPreviewShowcase",
    verifiedAt: "2026-08-13",
    expiresAt: "2027-08-13",
    owner: "HairFit product",
  },
  {
    id: "EVD-PREVIEW-9",
    status: "verified",
    statement: "현재 V2 컨설팅과 랜딩은 아홉 개의 헤어 후보 보드를 제품 증거로 사용한다.",
    sourceRef: "my-app/lib/landing-premium-contract.test.ts#proof-artifacts",
    verifiedAt: "2026-08-13",
    expiresAt: "2027-08-13",
    owner: "HairFit frontend",
  },
  {
    id: "EVD-SHORTLIST-3",
    status: "verified",
    statement: "사용자는 아홉 후보에서 최대 세 개의 shortlist를 구성할 수 있다.",
    sourceRef: "packages/shared/src/v2/preview-board/contract.ts",
    verifiedAt: "2026-08-12",
    expiresAt: "2027-08-12",
    owner: "HairFit V2",
  },
  {
    id: "EVD-COMPARE-2",
    status: "verified",
    statement: "결정 단계는 최소 두 개의 후보 비교를 지원한다.",
    sourceRef: "my-app/components/consulting/workbenches/CompareWorkbench.tsx",
    verifiedAt: "2026-08-12",
    expiresAt: "2027-08-12",
    owner: "HairFit V2",
  },
  {
    id: "EVD-SALON-BRIEF",
    status: "verified",
    statement: "선택한 방향과 상담 정보는 Salon Brief 화면으로 연결된다.",
    sourceRef: "my-app/components/consulting/workbenches/BriefWorkbench.tsx",
    verifiedAt: "2026-08-12",
    expiresAt: "2027-08-12",
    owner: "HairFit V2",
  },
  {
    id: "EVD-RESULT-LIMIT",
    status: "verified",
    statement: "AI 후보는 의사결정을 돕는 시각 자료이며 실제 시술 결과를 보장하지 않는다.",
    sourceRef: "docs/hairfit-v2-premium-landing-baseline-2026-08-12.md",
    verifiedAt: "2026-08-12",
    expiresAt: "2027-08-12",
    owner: "HairFit product",
  },
  {
    id: "EVD-AI-SIM-CANARY",
    status: "verified",
    statement: "공개 discovery 템플릿은 정적 HTML, canonical, JSON-LD와 상담 CTA 계약을 함께 제공한다.",
    sourceRef: "my-app/lib/discovery/discovery-contract.test.ts",
    verifiedAt: "2026-08-14",
    expiresAt: "2027-08-14",
    owner: "HairFit frontend",
  },
  {
    id: "EVD-FACE-MEASUREMENT",
    status: "verified",
    statement: "얼굴 관찰 근거는 정규화된 얼굴 길이, 이마·광대·턱 폭과 비율을 버전된 분석 계약으로 표현한다.",
    sourceRef: "packages/shared/src/v2/analysis/geometry.ts#buildAnalysisEvidenceV2",
    verifiedAt: "2026-08-14",
    expiresAt: "2027-08-14",
    owner: "HairFit V2 analysis",
  },
  {
    id: "EVD-MEN-CONTINUITY",
    status: "verified",
    statement: "남성 샘플 보드는 같은 기준 인물로 아홉 개 후보를 구성하는 전용 continuity set을 사용한다.",
    sourceRef: "my-app/components/home/PremiumAutoSwitchPreviewPanel.tsx#malePreviews",
    verifiedAt: "2026-08-14",
    expiresAt: "2027-08-14",
    owner: "HairFit product design",
  },
  {
    id: "EVD-WOMEN-CONTINUITY",
    status: "verified",
    statement: "여성 샘플 보드는 같은 기준 인물에서 단발, 미디엄, 롱 후보를 비교하는 전용 continuity set을 사용한다.",
    sourceRef: "my-app/components/home/PremiumAutoSwitchPreviewPanel.tsx#femalePreviews",
    verifiedAt: "2026-08-14",
    expiresAt: "2027-08-14",
    owner: "HairFit product design",
  },
  {
    id: "EVD-FRINGE-AXIS",
    status: "verified",
    statement: "HairFit 방향 조정 계약은 앞머리를 open, side, full 축으로 명시적으로 다룬다.",
    sourceRef: "my-app/components/consulting/workbenches/DirectionWorkbench.tsx#fringe",
    verifiedAt: "2026-08-14",
    expiresAt: "2027-08-14",
    owner: "HairFit V2 consulting",
  },
  {
    id: "EVD-LENGTH-AXIS",
    status: "verified",
    statement: "HairFit 방향 조정 계약은 길이를 short, medium, long 축으로 명시적으로 다룬다.",
    sourceRef: "my-app/components/consulting/workbenches/DirectionWorkbench.tsx#length",
    verifiedAt: "2026-08-14",
    expiresAt: "2027-08-14",
    owner: "HairFit V2 consulting",
  },
  {
    id: "EVD-SALON-BRIEF-VERSION",
    status: "verified",
    statement: "Salon Brief는 상담 요청과 제약 조건을 수정할 때 새 버전으로 저장하는 화면 계약을 가진다.",
    sourceRef: "my-app/components/consulting/workbenches/BriefWorkbench.tsx#updateBrief",
    verifiedAt: "2026-08-14",
    expiresAt: "2027-08-14",
    owner: "HairFit V2 consulting",
  },
  {
    id: "EVD-MAKEUP-COLOR-GROUNDING",
    status: "verified",
    statement: "확정 메이크업 방향은 퍼스널 컬러 근거와 확정 헤어, 사용자 요구를 구조화된 입력으로 연결한다.",
    sourceRef: "my-app/components/consulting/makeup/MakeupDirectionFixture.tsx#professionalReportInput",
    verifiedAt: "2026-08-22",
    expiresAt: "2027-08-22",
    owner: "HairFit makeup direction",
  },
  {
    id: "EVD-MAKEUP-ROUTINE-BRIEF",
    status: "verified",
    statement: "확정 메이크업 방향은 셀프 적용 루틴과 아티스트용 부위별 명세로 함께 제공된다.",
    sourceRef: "my-app/components/consulting/makeup/MakeupDirectionFixture.tsx#routine",
    verifiedAt: "2026-08-22",
    expiresAt: "2027-08-22",
    owner: "HairFit makeup direction",
  },
  {
    id: "EVD-MAKEUP-PROFESSIONAL-REPORT",
    status: "verified",
    statement: "확정 메이크업 방향에는 고객용 AI 전문 해설과 권위 데이터인 전문가 명세가 같은 화면에서 제공된다.",
    sourceRef: "my-app/components/consulting/makeup/MakeupDirectionFixture.tsx#MakeupProfessionalReport",
    verifiedAt: "2026-08-22",
    expiresAt: "2027-08-22",
    owner: "HairFit makeup report",
  },
] satisfies readonly DiscoveryEvidenceEntry[];

export function getDiscoveryEvidence(id: string) {
  return discoveryEvidenceRegistry.find((entry) => entry.id === id);
}
