/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/report-pdf/wrangler.jsonc --include-runtime=false --env-interface=ReportPdfEnv workers/report-pdf/worker-configuration.d.ts` (hash: 0db3d7ece83f594ea2f046f04a536842)
interface __BaseEnv_ReportPdfEnv {
	REPORT_PDF_ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_ReportPdfEnv {}
}
interface ReportPdfEnv extends __BaseEnv_ReportPdfEnv {}
